name: backend pipeline 
on:
  push:
     branches: [ main ]
     paths:
       - 'backend/**'
  workflow_dispatch:
jobs:
  test:
    runs-on: ubuntu-latest
    defaults:
     run:
       working-directory: ./backend
    steps:
      - name: checkout code
        uses: actions/checkout@v4
      - name: setup php
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          extensions: mbstring, xml, ctype
      - name: Install dependencies
        run: composer install
      - name: run phpUnit test
        run: vendor/bin/phpunit tests
      - run: echo "Test is successfull"
  build_push:
    needs: test
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./backend
    steps:
      - name: checkout code
        uses: actions/checkout@v4
      - name: docker login
        uses: docker/login-action@v4
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: build and push
        uses: docker/build-push-action@v6
        with:
          context: ./backend
          file: ./backend/Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/my-backend:latest
  deploy:
    needs: build_push   
    runs-on: self-hosted
    steps:
      - name: pull the image from docker hub
        run:  docker pull ${{ secrets.DOCKER_USERNAME }}/my-backend:latest
      - name: set .env in runner
        run: |
         echo " DB_PASSWORD=${{secrets.DB_PASSWORD}}" > .env
         echo " DB_NAME=${{secrets.DB_NAME}}" >> .env
         echo " PORT=${{secrets.PORT}}" >> .env
         echo " HOST=${{secrets.HOST}}" >> .env
      - name: deploying on the docker
        run: |
          docker stop backend_container || true
          docker rm backend_container || true
          docker run -d --name backend_container -p 80:80 --env .env ${{ secrets.DOCKER_USERNAME }}/my-backend:latest
     
    
  
   
     
